---
title: "RMarkdown zero"
author: "William Mailil"
date: "01-05-2026"
output: "html_document"
---
##libraries
```{r}
library(sf)
library(arrow)
library(tidyverse)
```

##**Loading and viewing GIST**
```{r}
GI_metadata <- read_csv("data/GI_metadata.csv")
GIST <- read_parquet("data/GIST_v1-1.parquet")
```

##testing transliteration one a-piece
```{r}
# GIST %>%
#   filter(str_detect(lemmata, regex("ὑπηρέτης",ignore_case = TRUE))) %>%
#   select(lemmata)
  
  
#μαία 1477 matches
#Μαῖα 44
#μαῖα 44
#ὑπηρέτησ 144
#ὑπηρέτης 144
#υπηρέτης 17

```

##trying to load my whole catalogue and apply it
```{r}
occupation <- read_csv2("data/occupations_translit_v1-5.csv")
# ok now to combine the two

# I added \\b to the start and end to ensure an exact match, because later on when I was using left_join there would be a discrepancy between words that were matched and words that were assigned a value. I discovered that it was because the words would start or end with a character that could be matched by the former pattern, but not by the left_join and would therefore be assigned NA.
pattern <- paste(occupation$term_greek_transliterated, collapse = "|")
GIST %>% 
  filter(str_detect(lemmata, regex(pattern, ignore_case = TRUE))) %>% 
  select(lemmata)


# i think this is something called partial matching, which doesn't sound great, but it works with 9371 matches, which is something
# ok i have found the occupation carpenter, ferryman, secretary, doctor, architect and cook so it can't be that bad. there is something relevant in every line and it is not "parital"
# what should i do with this? i can still add more occupations independent of lewis and harris. adela suggested priest
# note: i have 14.638 now that is more than a 50% increase, more fiddling is prob a good idea, the inclusion of the occupation priest specifically is responsible for this. How do i know priest refers to occupation on these inscriptions? I don't but i don't know for the other occupations either.
# i have 14.671 now after going over my catalogue again
# 10.526 after hopefully final look

```

##extracting matches with corresponding row
```{r}
# this is going to take forever, but it works
GIST %>% 
  filter(str_detect(lemmata, regex(pattern, ignore_case = TRUE))) %>% 
  mutate(matched_terms = str_extract_all(lemmata, regex(pattern, ignore_case = TRUE))) %>%
  select(matched_terms, everything()) -> GIST_matched

```


##trying to unnest the matched_terms
```{r}
# with dublicates
# GIST_matched_unnested_all <- GIST_matched %>%
  # unnest(matched_terms)
# gives 23818 because of dublicates

# but it is probably best i unnest only uniques and not also dublicates.
# this removes the dublicates before unnesting
GIST_matched_unnested <- GIST_matched %>%
  mutate(matched_terms = lapply(matched_terms, unique)) %>%
  unnest(matched_terms)
# gives 11783
# gives 13216 now


# testing
# GIST_matched_unnested %>%
# filter(str_detect(matched_terms, regex("ἱερεύς",ignore_case = TRUE))) %>%
#   select(matched_terms)
# GIST_matched gives 0 for ἱερεύς becuz i removed it :)
```



##wrangling the data
```{r}
# i should fit them after the urban_context, urban_context_city and urban_context_pop_est
# i no long think i will be making maps so no need for is_geotemporal and the others
GIST_matched_unnested %>%
  select(matched_terms, not_after, not_before, urban_context, urban_context_city, urban_context_pop_est, PHI_ID) -> GIST_matched_unnested_urban_contexts
# alright i should get on working sectors and hisco into the dataset
# i should do the filter(not_after<1454&not_before>-801)%>% piecemeal

```


##final results
```{r}
GIST_results <- GIST_matched_unnested_urban_contexts %>%
  left_join(occupation %>% 
              select(term_greek_transliterated, translation_eng, hisco_major, harris_sector), by = c("matched_terms" = "term_greek_transliterated"))
# nice.


# defining the periods
# periods <- tibble::tribble( ~period, ~start, ~end, "Archaic", -800, -500, "Classical", -499, -323, "Hellenistic", -322, -30)
# 
# # i should dive it into time periods now
# # archaic
# GIST_results %>%
#   filter(not_after>=-800&not_before<=-500) -> GIST_results_archaic_old
# 
#   # classical
# GIST_results %>%
#   filter(not_after>=-499&not_before<=-323) -> GIST_results_classical_old
# 
# # hellenistic
# GIST_results %>%
#   filter(not_after>=-322&not_before<=-30) -> GIST_results_hellenistic_old

# 
# # lets see what the mean value is. keep in mind that i exclude priest and priestess here because they have NA hisco_major value
# GIST_results %>%
#   filter(urban_context == "rural") %>%
#   pull(hisco_major) %>%
#   mean(na.rm = TRUE)
# ok 3.979031 that is significant

```





##plots
```{r}

```




##writting this into a .csv or no i should probably write this into a parquet
```{r}

# write_csv2(GIST_matched_neat, "data/GIST_matched_neat.csv")

# read_csv2("data/GIST_matched_neat.csv") -> read_GIST_matched_neat

# having trouble keeping the greek characters and geometry data intact
# i should probably write this into a parquet

write_parquet(GIST_matched_unnested_urban_contexts, "data/GIST_matched_unnested_urban_contexts.parquet")

read_parquet("data/GIST_matched_unnested_urban_contexts.parquet") -> read_GIST_matched_neat

# yeah parquet works!

```


